jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64 # 호환성 끝판왕 이미지
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          yum install -y cmake boost-devel imath-devel zlib-devel

          /opt/python/cp311-cp311/bin/pip install numpy

      - name: Build Alembic with Python Bindings
        run: |
          git clone https://github.com
          cd alembic
          mkdir build && cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX=./install \
            -DUSE_PYALEMBIC=ON \
            -DUSE_PYIMATH=ON \
            -DPYTHON_EXECUTABLE=/opt/python/cp311-cp311/bin/python \
            -DALEMBIC_LIB_INSTALL_DIR=lib \
            -DPYALEMBIC_PYTHON_VERSION=3.11
          make -j$(nproc)
          make install
